cmake_minimum_required(VERSION 3.21)
function(run stage)
    execute_process(COMMAND ${ARGN} RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if (NOT result STREQUAL "0")
        message(FATAL_ERROR "${stage} failed (${result}).\n${output}\n${error}")
    endif ()
endfunction()
cmake_path(ABSOLUTE_PATH SERVERCORE_PACKAGE_BINARY_DIR NORMALIZE OUTPUT_VARIABLE producer)
cmake_path(ABSOLUTE_PATH SERVERCORE_PACKAGE_TEST_ROOT NORMALIZE OUTPUT_VARIABLE testRoot)
cmake_path(IS_PREFIX producer "${testRoot}" NORMALIZE inside)
if (NOT inside OR producer STREQUAL testRoot)
    message(FATAL_ERROR "The consumer must be strictly inside its producer build.")
endif ()
file(REMOVE_RECURSE "${testRoot}")
run("Install C ABI only" "${CMAKE_COMMAND}" --install "${producer}"
    --config "${SERVERCORE_PACKAGE_CONFIGURATION}" --component CAbi --prefix "${testRoot}/stage")
file(RENAME "${testRoot}/stage" "${testRoot}/relocated")

# The component must be independently relocatable with one implementation
# binary. ELF SONAME symlinks may name the same file more than once.
set(packagePrefix "${testRoot}/relocated")
file(GLOB_RECURSE installedFiles LIST_DIRECTORIES FALSE "${packagePrefix}/*")
set(runtimeBinaries)
foreach (installedFile IN LISTS installedFiles)
    cmake_path(GET installedFile FILENAME installedName)
    if (installedName MATCHES "^(lib)?ServerCoreCAbi(d)?\\.(dll|lib|a|so)(\\..*)?$")
        message(FATAL_ERROR "The single-library package must not install a C ABI adapter binary: ${installedFile}")
    endif ()
    if (installedName MATCHES "\\.dll$" OR installedName MATCHES "\\.so(\\..*)?$")
        if (NOT installedName MATCHES "^(lib)?ServerCore(d)?\\.(dll|so)(\\..*)?$")
            message(FATAL_ERROR "Unexpected shared binary in the C ABI component: ${installedFile}")
        endif ()
        file(REAL_PATH "${installedFile}" physicalBinary)
        cmake_path(IS_PREFIX packagePrefix "${physicalBinary}" NORMALIZE binaryInsidePackage)
        if (NOT binaryInsidePackage OR NOT EXISTS "${physicalBinary}")
            message(FATAL_ERROR "The shared library must remain inside the relocated package: ${installedFile}")
        endif ()
        list(APPEND runtimeBinaries "${physicalBinary}")
    endif ()
endforeach ()
list(REMOVE_DUPLICATES runtimeBinaries)
list(LENGTH runtimeBinaries runtimeBinaryCount)
if (NOT runtimeBinaryCount EQUAL 1)
    message(FATAL_ERROR "The C ABI component must contain exactly one shared implementation binary; found ${runtimeBinaryCount}.")
endif ()

# Types.h의 "No C++ exception crosses this ABI"는 모든 SC_API 선언이 SC_NOEXCEPT로 끝나는
# 것에 기댄다. 설치된 헤더에서 주석과 전처리 줄을 걷어 낸 뒤 선언을 하나씩 확인한다. CMake는
# ';'를 목록 구분자로 쓰므로 먼저 다른 표지로 바꾼다. 선언을 하나도 찾지 못하면 이 검사가 헛돈
# 것이므로 그것도 실패로 본다.
file(GLOB_RECURSE installedCHeaders LIST_DIRECTORIES FALSE "${packagePrefix}/*/ServerCore/C/*.h")
set(declarationCount 0)
foreach (header IN LISTS installedCHeaders)
    file(READ "${header}" text)
    string(REPLACE ";" "@SEMICOLON@" text "${text}")
    string(REGEX REPLACE "/\\*([^*]|\\*+[^*/])*\\*+/" "" text "${text}")
    string(REGEX REPLACE "#[^\n]*" "" text "${text}")
    string(REGEX MATCHALL "SC_API[^@]*@SEMICOLON@" declarations "${text}")
    foreach (declaration IN LISTS declarations)
        math(EXPR declarationCount "${declarationCount} + 1")
        if (NOT declaration MATCHES "\\)[ \t\r\n]*SC_NOEXCEPT[ \t\r\n]*@SEMICOLON@$")
            string(REPLACE "@SEMICOLON@" ";" declaration "${declaration}")
            message(FATAL_ERROR "An installed C ABI declaration lacks SC_NOEXCEPT in ${header}:\n${declaration}")
        endif ()
    endforeach ()
endforeach ()
if (declarationCount EQUAL 0)
    message(FATAL_ERROR "No SC_API declaration was found in the installed C ABI headers.")
endif ()

set(command "${CMAKE_COMMAND}" -S "${SERVERCORE_PACKAGE_SOURCE_DIR}/tests/CAbiConsumer"
    -B "${testRoot}/consumer" -G "${SERVERCORE_PACKAGE_GENERATOR}"
    "-DSERVERCORE_PACKAGE_PREFIX=${testRoot}/relocated")
if (SERVERCORE_PACKAGE_GENERATOR_PLATFORM)
    list(APPEND command -A "${SERVERCORE_PACKAGE_GENERATOR_PLATFORM}")
endif ()
if (SERVERCORE_PACKAGE_GENERATOR_TOOLSET)
    list(APPEND command -T "${SERVERCORE_PACKAGE_GENERATOR_TOOLSET}")
endif ()
if (SERVERCORE_PACKAGE_TOOLCHAIN_FILE)
    list(APPEND command "-DCMAKE_TOOLCHAIN_FILE=${SERVERCORE_PACKAGE_TOOLCHAIN_FILE}")
endif ()
if (SERVERCORE_PACKAGE_MAKE_PROGRAM)
    list(APPEND command "-DCMAKE_MAKE_PROGRAM=${SERVERCORE_PACKAGE_MAKE_PROGRAM}")
endif ()
list(APPEND command "-DCMAKE_BUILD_TYPE=${SERVERCORE_PACKAGE_CONFIGURATION}")
run("Configure pure C consumer" ${command})
run("Build pure C consumer" "${CMAKE_COMMAND}" --build "${testRoot}/consumer" --config "${SERVERCORE_PACKAGE_CONFIGURATION}")
if (NOT SERVERCORE_PACKAGE_CROSSCOMPILING)
    run("Execute pure C consumer" "${SERVERCORE_PACKAGE_CTEST_COMMAND}" --test-dir "${testRoot}/consumer"
        -C "${SERVERCORE_PACKAGE_CONFIGURATION}" --output-on-failure --no-tests=error)
endif ()
