# Check direct repository-owned includes, including inactive platform branches.
# This is an architectural regression check, not a C++ parser or a link checker.
cmake_minimum_required(VERSION 3.21)

if (NOT DEFINED SERVERCORE_LAYER_SOURCE_DIR)
    get_filename_component(SERVERCORE_LAYER_SOURCE_DIR "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
endif ()
cmake_path(ABSOLUTE_PATH SERVERCORE_LAYER_SOURCE_DIR NORMALIZE OUTPUT_VARIABLE root)

function(layer_of path output)
    string(REGEX REPLACE "^(include/ServerCore|src)/" "" path "${path}")
    if (path STREQUAL "Export.h")
        set(layer Core)
    elseif (path MATCHES "^Observability/(Metrics|MetricsInternal|RequestTrace|Observation)\\.h$")
        set(layer Metrics)
    elseif (path MATCHES "^Observability/AsyncLogger\\.(h|cpp)$")
        set(layer Logging)
    elseif (path MATCHES "^Observability/Prometheus\\.(h|cpp)$")
        set(layer Export)
    elseif (path MATCHES "^Observability/ServerObservation\\.(h|cpp)$")
        set(layer ObservationExport)
    elseif (path MATCHES "^Runtime/(JobRunner|TaskExecutor|PeriodicRunner|KeyedExecutor|TimerScheduler|TaskGroup|Channel|CompletionSignalInternal|RequestLimiter|TickRunner|ExecutionTestAccess)\\.(h|cpp)$")
        set(layer Execution)
    elseif (path STREQUAL "Runtime/Metrics.h")
        set(layer HostMetrics)
    elseif (path MATCHES "^Runtime/")
        set(layer Host)
    elseif (path MATCHES "^(Core|Net|Protocol|Session|Dispatch|Web|C)/")
        set(layer "${CMAKE_MATCH_1}")
    else ()
        message(FATAL_ERROR "Unclassified ServerCore layer: ${path}. Assign its dependency boundary explicitly.")
    endif ()
    set(${output} "${layer}" PARENT_SCOPE)
endfunction()

# Every boundary is directional. Runtime contains both generic execution and
# higher-level Host composition; Observability contains leaf contracts and a
# snapshot export adapter. Folder names alone cannot express these boundaries.
set(allowed_Core Core)
set(allowed_Metrics Metrics Core)
set(allowed_Logging Logging Core Metrics)
set(allowed_Net Net Core)
set(allowed_Protocol Protocol Core)
set(allowed_Session Session Protocol Core)
set(allowed_Dispatch Dispatch Session Protocol Core)
set(allowed_Execution Execution Metrics Core)
set(allowed_HostMetrics HostMetrics Session Metrics Core)
set(allowed_Host Host HostMetrics Execution Dispatch Session Protocol Net Metrics Core)
set(allowed_Web Web Execution Net Protocol Metrics Core)
set(allowed_Export Export HostMetrics Metrics Core)
set(allowed_ObservationExport ObservationExport Web Host HostMetrics Execution Net Metrics Logging Core)
set(allowed_C C Web Host HostMetrics Execution Dispatch Session Protocol Net Metrics Logging Export ObservationExport Core)

file(GLOB_RECURSE sources RELATIVE "${root}"
        "${root}/include/ServerCore/*.h" "${root}/include/ServerCore/*.hpp"
        "${root}/src/*.h" "${root}/src/*.hpp" "${root}/src/*.cpp" "${root}/src/*.cc" "${root}/src/*.c")
if (NOT sources)
    message(FATAL_ERROR "No ServerCore sources to check in ${root}")
endif ()
set(count 0)
foreach(source IN LISTS sources)
    # This translation unit intentionally includes every public boundary.
    if (source STREQUAL "src/PublicHeaderCompileCheck.cpp")
        continue()
    endif ()
    layer_of("${source}" owner)
    get_filename_component(directory "${root}/${source}" DIRECTORY)
    file(STRINGS "${root}/${source}" lines REGEX "^[ \t]*#[ \t]*include[ \t]*[\"<]")
    foreach(line IN LISTS lines)
        if (NOT line MATCHES "^[ \t]*#[ \t]*include[ \t]*[\"<]([^\">]+)[\">]")
            continue()
        endif ()
        set(header "${CMAKE_MATCH_1}")
        set(resolved "")
        foreach(candidate IN ITEMS "${directory}/${header}" "${root}/include/${header}" "${root}/src/${header}")
            if (EXISTS "${candidate}")
                cmake_path(NORMAL_PATH candidate OUTPUT_VARIABLE resolved)
                break()
            endif ()
        endforeach()
        if (resolved STREQUAL "")
            # Standard library and OS headers are not repository-owned.
            continue()
        endif ()
        file(RELATIVE_PATH dependency "${root}" "${resolved}")
        layer_of("${dependency}" target)
        if (NOT target IN_LIST allowed_${owner})
            message(FATAL_ERROR "Layer violation: ${source} (${owner}) includes ${dependency} (${target})")
        endif ()
        if (source MATCHES "^include/" AND dependency MATCHES "^src/")
            message(FATAL_ERROR "Public header ${source} exposes private implementation ${dependency}")
        endif ()
        # DatagramTransport is the sole upper-layer owner of this private raw
        # UDP contract; it has no public raw-socket API. Platform connection and
        # acceptor internals must stay inside Net.
        if (dependency MATCHES "^src/Net/" AND NOT owner STREQUAL "Net"
                AND NOT (source STREQUAL "src/Runtime/DatagramTransport.cpp"
                         AND dependency STREQUAL "src/Net/DatagramSocket.h"))
            message(FATAL_ERROR "${source} accesses Net internals ${dependency}; use the public transport API")
        endif ()
        math(EXPR count "${count} + 1")
    endforeach()
endforeach()
message(STATUS "ServerCore layering: ${count} repository includes checked")
